name: CD - Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI - Continuous Integration"]
    types:
      - completed
    branches: [ main ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/clima-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event.workflow_run.conclusion == 'success')
    environment: production

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Instalar dependências
      run: npm ci

    - name: Build da aplicação
      run: npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Debug - Verificar variáveis
      run: |
        echo "🔍 Debug: Verificando variáveis de ambiente"
        echo "REGISTRY: ${{ env.REGISTRY }}"
        echo "IMAGE_NAME: ${{ env.IMAGE_NAME }}"
        echo "DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_SHA: ${{ github.sha }}"

    - name: Extrair metadados
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,prefix=sha-

    - name: Debug - Verificar tags geradas
      run: |
        echo "🔍 Debug: Tags geradas pelo metadata-action"
        echo "Tags: ${{ steps.meta.outputs.tags }}"
        echo "Labels: ${{ steps.meta.outputs.labels }}"

    - name: Build e push da imagem Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Deploy para Vercel
    - name: Deploy para Vercel
      if: vars.DEPLOY_TARGET == 'vercel'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'

    # Notificações de sucesso
    - name: Notificar sucesso do deploy
      if: success()
      run: |
        echo "✅ Deploy realizado com sucesso!"
        echo "📋 Build ID: ${{ github.run_id }}"
        echo "🔗 Commit: ${{ github.sha }}"
        echo "👤 Autor: ${{ github.actor }}"
        echo "📅 Data: $(date)"
        echo "🐳 Imagem Docker: ${{ env.IMAGE_NAME }}:${{ github.sha }}"
        
        # Aqui você pode adicionar notificações (Slack, Discord, etc.)
        # curl -X POST -H 'Content-type: application/json' \
        #   --data '{"text":"✅ Deploy realizado com sucesso! Build #${{ github.run_number }}"}' \
        #   ${{ secrets.SLACK_WEBHOOK_URL }}

    # Notificações de falha
    - name: Notificar falha no deploy
      if: failure()
      run: |
        echo "❌ Falha no deploy!"
        echo "📋 Build ID: ${{ github.run_id }}"
        echo "🔗 Commit: ${{ github.sha }}"
        echo "👤 Autor: ${{ github.actor }}"
        echo "📅 Data: $(date)"
        
        # Aqui você pode adicionar notificações de falha
        # curl -X POST -H 'Content-type: application/json' \
        #   --data '{"text":"❌ Falha no deploy! Build #${{ github.run_number }}"}' \
        #   ${{ secrets.SLACK_WEBHOOK_URL }}